linters:
  enable:
    - asciicheck
    - godot
    - cyclop
    - gomnd
    - bodyclose
    - unused
    - gochecknoglobals
    - gocritic
    - gofmt
    - goimports
    - revive

linters-settings:
  cyclop:
    max-complexity: 10
