version: '3.9'
services:
  app:
    build:
      dockerfile: ./Dockerfile.local
      context: .
    container_name: flight-path-tracker-app
    ports:
      - "8080:8080"

  test:
    build:
      dockerfile: ./Dockerfile.test
      context: .
